name: Run 40 Automations

on: push

jobs:
  run-automations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        automation-number: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - uses: actions/checkout@v4

      - name: Run Automation ${{ matrix.automation-number }}
        run: echo automation-${{ matrix.automation-number }}
